#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
wmname LG3D &
nitrogen --restore
$HOME/.config/polybar/launch.sh custom-theme
picom --experimental-backends &

bspc monitor DP-0 -d I II III IV V
bspc monitor HDMI-0 -d VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
