#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
wmname LG3D &
feh --bg-fill ~/Pictures/Wallpapers/wallpaper.jpg &
picom --experimental-backends &
$HOME/.config/polybar/launch.sh custom-theme
nvidia-settings -a "[gpu:0]/GPUFanControlState=1" -a "[fan:0]/GPUTargetFanSpeed=70" > /dev/null &
nvidia-settings -a "[gpu:0]/GPUPowerMizerMode=0" > /dev/null &
pgrep -x redshift > /dev/null || redshift &
pgrep -x lxpolkit > /dev/null || lxpolkit &

bspc monitor DP-0 -d I II III IV V
bspc monitor HDMI-0 -d VI VII VIII IX X

bspc config border_width                0
bspc config window_gap                  8
bspc config pointer_modifier            mod4
bspc config pointer_action1             move
bspc config pointer_action2             resize_side
bspc config pointer_action3             resize_corner
bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true
